Repository Aryankpoor/Order-delivery, pull requests merged in 2023-10, with the labels that each got.

#33 Added Back to top
  Index.html
  assets/css/style.css
  assets/images/hero-banner.jpg
Labels: hacktoberfest

#36 Fixed UI Issues
  Index.html
  assets/css/style.css
Labels: hacktoberfest

#41 Update README.md
  README.md
Labels: documentation, hacktoberfest

#44 Update style.css
  assets/css/style.css
Labels: enhancement, hacktoberfest
